-- MySQL Script generated by MySQL Workbench
-- Fri Oct  6 21:24:59 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema porkydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `porkydb` ;

-- -----------------------------------------------------
-- Schema porkydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `porkydb` DEFAULT CHARACTER SET utf8 ;
USE `porkydb` ;

-- -----------------------------------------------------
-- Table `porkydb`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `porkydb`.`categoria` ;

CREATE TABLE IF NOT EXISTS `porkydb`.`categoria` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `porkydb`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `porkydb`.`producto` ;

CREATE TABLE IF NOT EXISTS `porkydb`.`producto` (
  `codigo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `precio` FLOAT NULL,
  `id_categoria` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  CONSTRAINT `fk_producto_categoria1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `porkydb`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `porkydb`.`receta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `porkydb`.`receta` ;

CREATE TABLE IF NOT EXISTS `porkydb`.`receta` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `tiempo_prep` INT NOT NULL,
  `porciones` INT NOT NULL,
  `codigo_producto` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_receta_producto1`
    FOREIGN KEY (`codigo_producto`)
    REFERENCES `porkydb`.`producto` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `porkydb`.`paso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `porkydb`.`paso` ;

CREATE TABLE IF NOT EXISTS `porkydb`.`paso` (
  `numero` INT UNSIGNED NOT NULL,
  `instruccion` TEXT(400) NOT NULL,
  `id_receta` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`numero`, `id_receta`),
  CONSTRAINT `fk_paso_receta1`
    FOREIGN KEY (`id_receta`)
    REFERENCES `porkydb`.`receta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `porkydb`.`ingrediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `porkydb`.`ingrediente` ;

CREATE TABLE IF NOT EXISTS `porkydb`.`ingrediente` (
  `codigo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `porkydb`.`ingredientesxreceta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `porkydb`.`ingredientesxreceta` ;

CREATE TABLE IF NOT EXISTS `porkydb`.`ingredientesxreceta` (
  `id_receta` INT UNSIGNED NOT NULL,
  `codigo_ingrediente` INT UNSIGNED NOT NULL,
  `cantidad` INT NULL,
  `tipo_unidad` VARCHAR(15) NULL,
  PRIMARY KEY (`id_receta`, `codigo_ingrediente`),
  CONSTRAINT `fk_receta_has_ingrediente_receta1`
    FOREIGN KEY (`id_receta`)
    REFERENCES `porkydb`.`receta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receta_has_ingrediente_ingrediente1`
    FOREIGN KEY (`codigo_ingrediente`)
    REFERENCES `porkydb`.`ingrediente` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `porkydb`.`metodo_de_pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `porkydb`.`metodo_de_pago` ;

CREATE TABLE IF NOT EXISTS `porkydb`.`metodo_de_pago` (
  `id` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `porkydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `porkydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `porkydb`.`usuario` (
  `nombre_usuario` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`nombre_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `porkydb`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `porkydb`.`pedido` ;

CREATE TABLE IF NOT EXISTS `porkydb`.`pedido` (
  `numero` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha_pedido` DATE NOT NULL,
  `fecha_entrega` DATE NULL,
  `comentario` TEXT(200) NULL,
  `id_metodo_de_pago` INT UNSIGNED NOT NULL,
  `nombre_usuario` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`numero`),
  CONSTRAINT `fk_pedido_metodo_de_pago1`
    FOREIGN KEY (`id_metodo_de_pago`)
    REFERENCES `porkydb`.`metodo_de_pago` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_usuario1`
    FOREIGN KEY (`nombre_usuario`)
    REFERENCES `porkydb`.`usuario` (`nombre_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `porkydb`.`productosxpedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `porkydb`.`productosxpedido` ;

CREATE TABLE IF NOT EXISTS `porkydb`.`productosxpedido` (
  `codigo_producto` INT UNSIGNED NOT NULL,
  `numero_pedido` INT UNSIGNED NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`codigo_producto`, `numero_pedido`),
  CONSTRAINT `fk_producto_has_pedido_producto1`
    FOREIGN KEY (`codigo_producto`)
    REFERENCES `porkydb`.`producto` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_has_pedido_pedido1`
    FOREIGN KEY (`numero_pedido`)
    REFERENCES `porkydb`.`pedido` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `porkydb`.`estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `porkydb`.`estado` ;

CREATE TABLE IF NOT EXISTS `porkydb`.`estado` (
  `id` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `porkydb`.`estadoxpedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `porkydb`.`estadoxpedido` ;

CREATE TABLE IF NOT EXISTS `porkydb`.`estadoxpedido` (
  `numero_pedido` INT UNSIGNED NOT NULL,
  `id_estado` INT UNSIGNED NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`numero_pedido`, `id_estado`),
  CONSTRAINT `fk_pedido_has_estado_pedido1`
    FOREIGN KEY (`numero_pedido`)
    REFERENCES `porkydb`.`pedido` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_has_estado_estado1`
    FOREIGN KEY (`id_estado`)
    REFERENCES `porkydb`.`estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `porkydb`.`recetasbasexreceta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `porkydb`.`recetasbasexreceta` ;

CREATE TABLE IF NOT EXISTS `porkydb`.`recetasbasexreceta` (
  `id_receta_principal` INT UNSIGNED NOT NULL,
  `id_receta_base` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_receta_principal`),
  CONSTRAINT `fk_receta_has_receta_receta1`
    FOREIGN KEY (`id_receta_principal`)
    REFERENCES `porkydb`.`receta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receta_has_receta_receta2`
    FOREIGN KEY (`id_receta_base`)
    REFERENCES `porkydb`.`receta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
